version: "3.8"
services:
  mongodb:
    image: arm64v8/mongo:4.4.18
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    ports:
      - 27017:27017

  automatedtradingsystem:
    image: automatedtradingsystem
    container_name: automatedtradingsystem
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_HOST: mongodb
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_USERNAME: rootuser
      SPRING_DATA_MONGODB_PASSWORD: rootpass
      SPRING_DATA_MONGODB_DATABASE: automatedtradingsystem
      SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: admin
      POLYGON_API_KEY: nHpbG6pe5P2T_zdiTL41vIqr58pxKvRp
      ALPACA_API_KEY_ID: PKY1GMJU6XRDRPMZJ1L9
      ALPACA_API_SECRET_KEY: cPaYLcWZmbTfahS3tfBpvy4CSrF9ity8TYknZVdt
    ports:
      - 8080:8080

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  data: {}

networks:
  default:
    name: mongodb_network