name: CI - Automated Trading System

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set environment variables
        run: |
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> $GITHUB_ENV
          echo "POLYGON_API_KEY=${{ secrets.POLYGON_API_KEY }}" >> $GITHUB_ENV
          echo "ALPACA_API_KEY_ID=${{ secrets.ALPACA_API_KEY_ID }}" >> $GITHUB_ENV
          echo "ALPACA_API_SECRET_KEY=${{ secrets.ALPACA_API_SECRET_KEY }}" >> $GITHUB_ENV

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test
