name: CI - Automated Trading System

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build-and-test-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set environment variables
        run: |
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> $GITHUB_ENV
          echo "POLYGON_API_KEY=${{ secrets.POLYGON_API_KEY }}" >> $GITHUB_ENV
          echo "ALPACA_API_KEY_ID=${{ secrets.ALPACA_API_KEY_ID }}" >> $GITHUB_ENV
          echo "ALPACA_API_SECRET_KEY=${{ secrets.ALPACA_API_SECRET_KEY }}" >> $GITHUB_ENV

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

  build-and-test-ui:
    runs-on: ubuntu-latest

    steps:
      - name : Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install UI dependencies
        working-directory: ui
        run: npm install

      - name: Build UI
        working-directory: ui
        run: npm run build
